"""retencao_config (doc 16)

Revision ID: 0c1230b0b498
Revises: 3350670163e9
Create Date: 2026-07-04 18:59:31.254676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c1230b0b498'
down_revision: Union[str, None] = '3350670163e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retencao_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runs_reter_dias', sa.Integer(), server_default='90', nullable=False),
    sa.Column('inventarios_reter_dias', sa.Integer(), server_default='90', nullable=False),
    sa.Column('min_por_cliente', sa.Integer(), server_default='20', nullable=False),
    sa.Column('auto_limpeza', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('intervalo_horas', sa.Integer(), server_default='24', nullable=False),
    sa.Column('ultima_limpeza', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retencao_config')
    # ### end Alembic commands ###
