"""update: conteudo do bkp.py + flag canary

Revision ID: 3350670163e9
Revises: b656a01abdd1
Create Date: 2026-07-03 21:39:28.664564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3350670163e9'
down_revision: Union[str, None] = 'b656a01abdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('canary', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('updates', sa.Column('conteudo', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'conteudo')
    op.drop_column('clientes', 'canary')
    # ### end Alembic commands ###
