"""inicial: schema completo (doc 6)

Revision ID: b656a01abdd1
Revises: 
Create Date: 2026-07-03 21:30:06.165880
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b656a01abdd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('age_pubkey', sa.String(length=120), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('versao_script', sa.String(length=32), nullable=True),
    sa.Column('ultimo_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=True)
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=32), nullable=False),
    sa.Column('arquivo', sa.String(length=300), nullable=False),
    sa.Column('assinatura', sa.Text(), nullable=False),
    sa.Column('grupo_rollout', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versao')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('client_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=200), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'campo', name='uq_secret_cliente_campo')
    )
    op.create_index(op.f('ix_client_secrets_cliente_id'), 'client_secrets', ['cliente_id'], unique=False)
    op.create_table('comandos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comandos_cliente_id'), 'comandos', ['cliente_id'], unique=False)
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('conteudo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'versao', name='uq_config_cliente_versao')
    )
    op.create_index(op.f('ix_configs_cliente_id'), 'configs', ['cliente_id'], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_tokens_cliente_id'), 'enrollment_tokens', ['cliente_id'], unique=False)
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventarios_cliente_id'), 'inventarios', ['cliente_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('jobs_ok', sa.Integer(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('versao_config', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_cliente_id'), 'runs', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_cliente_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_inventarios_cliente_id'), table_name='inventarios')
    op.drop_table('inventarios')
    op.drop_index(op.f('ix_enrollment_tokens_cliente_id'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    op.drop_index(op.f('ix_configs_cliente_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_comandos_cliente_id'), table_name='comandos')
    op.drop_table('comandos')
    op.drop_index(op.f('ix_client_secrets_cliente_id'), table_name='client_secrets')
    op.drop_table('client_secrets')
    op.drop_table('usuarios')
    op.drop_table('updates')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
