"""cliente.plataforma (linux|windows)

Revision ID: d961d27c5fcd
Revises: 0c1230b0b498
Create Date: 2026-07-06 13:43:20.655147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd961d27c5fcd'
down_revision: Union[str, None] = '0c1230b0b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('plataforma', sa.String(length=16), server_default='linux', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'plataforma')
    # ### end Alembic commands ###
